# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('episode_number', models.IntegerField()),
                ('main_characters', models.TextField()),
                ('description', models.TextField()),
                ('poster', models.CharField(max_length=200)),
                ('hero_image', models.CharField(max_length=200)),
            ],
        ),
    ]
